### ISSUE TITLE
No error message for converting an empty file

### ISSUE THREAD

**Issue by tizreal** [Stan15/TAB2XML#10]
Area Path: Input Area
Severity: Medium
Priority: HIGH 
Assigned to: https://github.com/Stan15/TAB2XML
 
Reported By: Odunfa Temiloluwa
Reported On: 2021-03-24
Reason: Defect

Commit #: b8647e12611a91a52872f2d9663b9a352f7465ba
Environment: Windows 10, Eclipse IDE 2020 -12

Description:
There is no error message when there is nothing to convert and the convert button is clicked, instead it informs the user that it's converted and it saves am empty file.

Steps To Reproduce:
1) Open the program
2) Leave the Input field empty 
3) Click on convert
 
<img width="748" alt="empty" src="https://user-images.githubusercontent.com/68396714/112397201-0171ec80-8cd8-11eb-932b-6eb6ab2a3639.PNG">

Expected Result: If the Convert button is clicked when there is nothing in the Input Area, an error message should pop up telling the user that there is no text in the textArea.

**Comment by Stan15** [comment]
Hi. Thanks for letting us know. A feature has been implemented where the convert button is disabled until a measure is found in the text area. I believe this fixes the issue.
