### ISSUE TITLE
Program doesn't handle wrong formating

### ISSUE THREAD

**Issue by tizreal** [Stan15/TAB2XML#11]
Area Path: Input Area > Convert
Severity: Medium
Priority: HIGH
Assigned to: https://github.com/Stan15/TAB2XML

Reported By: Odunfa Temiloluwa
Reported On: 2021-03-24
Reason: Defect

Reported By: Odunfa Temiloluwa
Reported On: 2021-03-24
Reason: Formatting Error 

Commit #: https://github.com/Stan15/TAB2XML/commit/b8647e12611a91a52872f2d9663b9a352f7465ba
Environment: Windows 10, Eclipse IDE 2020 -12

Description:
Application should throw an error stating to the user that the formatting of the lines are wrong :

<img width="751" alt="lines" src="https://user-images.githubusercontent.com/68396714/112397905-59f5b980-8cd9-11eb-95d0-3c76ae486bc7.PNG">

Expected Result: Program should throw an error to the user stating that there is an error with the line format or the program should fix the line format itself after identifying it".

**Comment by Stan15** [comment]
Hi. Thank you for your input and contribution to improving our software. 

This is actually a side-effect of bug #4 . The error should be displayed if you hover over the measure, but it does not show the highlighting.
