### ISSUE TITLE
Help function does nothing

### ISSUE THREAD

**Issue by tizreal** [Stan15/TAB2XML#12]
Area Path: Help>User manual
Severity: Medium
Priority: Low
Assigned to: https://github.com/Stan15/TAB2XML

Reported By: Odunfa Temiloluwa
Reported On: 2021-03-24
Reason: Defect

Commit #: b8647e1
Environment: Windows 10, Eclipse IDE 2020 -12

Description:
The help button shows user manual but when it's clicked, nothing happens.

Steps To Reproduce:

1.)Open the program
2.)Click on help
3.)Click on User manual

![Screenshot (78)](https://user-images.githubusercontent.com/68396714/112398751-35024600-8cdb-11eb-8f7a-3d5a8c0b077e.png)

Expected Result: After the steps are being taken, the program should either open the user manual on the users screen or take the user to the github repositotry where the manual is.

**Comment by Stan15** [comment]
Hi. Thanks for letting us know. this functionality has been added in the latest version of our software.
