### ISSUE TITLE
Grace notes are not being parsed right

### ISSUE THREAD

**Issue by Abhirami-Venugopal** [Stan15/TAB2XML#13]
**ID# 13**

Who raised it: Abhirami Venugopal, abhirami@my.yorku.ca

Version: March 23,2021 version of software

Platform: Windows 10, Eclipse version 4.8.0, JavaSE-15

MusicXML viewer: SoundSlice 
(https://www.soundslice.com/musicxml-viewer/)

Reproduction:  
1.	Open the app
2.	Paste [guitar_grace.txt](https://github.com/Stan15/TAB2XML/files/6201154/guitar_grace.txt)  into the text area 
3.	Click the “Convert” button 
4.	Download the output file 
5.	Upload to SoundSlice to test

Expected: When the generated output file is uploaded onto SoundSlice, the sheet music would like this:
![a](https://user-images.githubusercontent.com/77309918/112398546-d6d56300-8cda-11eb-8ab8-fd1025f8ac37.png)

In the musicXML file itself, grace tag should be opened inside the 4th note. 
![bb](https://user-images.githubusercontent.com/77309918/112398609-f3719b00-8cda-11eb-8f4d-dd7b93da4c48.png)

Actual: When the output file is uploaded into SoundSplice, this is the sheet music generated. Notice that some notes before grace are wrong.
![a](https://user-images.githubusercontent.com/77309918/112399697-14d38680-8cdd-11eb-9804-c5b843465f4d.png)

In the musicXML file itself, no grace tag is opened inside the 4th note. I have highlighted the differences in yellow, the step and octave of the 4th note is generated wrong.
![cc](https://user-images.githubusercontent.com/77309918/112398654-07b59800-8cdb-11eb-8da4-d40e9d38447a.png)

Priority: Medium. Caprico Arabe doesn’t contain any grace notes thus you will be able to parse that without issues. However, grace notes are in the scope of this course thus the output must be corrected and grace tags must be generated in the right place. 

Severity: Medium. Grace notes don’t appear in all guitar tabs. The bug will be encountered only on occasion.

**Comment by Stan15** [comment]
Hi. thanks for letting us know. At the time, support for grace notes had not been added. However, grace notes support has been added in the latest version of our software.
