### ISSUE TITLE
Repeat Tags not created

### ISSUE THREAD

**Issue by Abhirami-Venugopal** [Stan15/TAB2XML#14]
**ID# 14**

Who raised it: Abhirami Venugopal, abhirami@my.yorku.ca

Version: March 23,2021 version of software

Platform: Windows 10, Eclipse version 4.8.0, JavaSE-15
MusicXML viewer: SoundSlice (https://www.soundslice.com/musicxml-viewer/)

Reproduction: 
1.	Paste the tab found in this to the text area.
2.	Click on the “Convert” button.
3.	Download the output file.

Expected: 
A musicXML file similar to this. When uploaded to SoundSlice, the output should look like this:
![a](https://user-images.githubusercontent.com/77309918/112398997-c5d92180-8cdb-11eb-9899-10d1835712cd.png)

In the musixXML document itself, the first note should look like this:
![bb](https://user-images.githubusercontent.com/77309918/112399021-d4273d80-8cdb-11eb-97da-0ec6039e526b.png)

Actual: Output file does not create any repeat tags. The output file generated contained several errors and appears to detect the step and octave of the notes wrong. 
![cc](https://user-images.githubusercontent.com/77309918/112399052-e5704a00-8cdb-11eb-9f8c-ffb3ecd4e41d.png)

In the musixXML document itself, the first note should look like this. Differences between this and expected is highlighted in yellow. 

![a](https://user-images.githubusercontent.com/77309918/112399257-4ef05880-8cdc-11eb-9998-02bbacb75152.png)

Priority: High. The bug needs to be fixed as soon as possible since most tabs contained repeated sections and it seems that repeats are confusing the parser and is giving a wrong output even for sections that are not repeated. 

Severity: High. This defect affects the overall functionality of the code and will be encountered quite often as most music tabs would contain repeated sections.

**Comment by Stan15** [comment]
Thanks for letting us know. Support for repeats has been added to our software. You can have a look at our user manual to see the two ways in which repeats can be notated.
