### ISSUE TITLE
Title, Artist, Conversion method does not work

### ISSUE THREAD

**Issue by Abhirami-Venugopal** [Stan15/TAB2XML#15]
**ID# 15**

Who raised it: Abhirami Venugopal, abhirami@my.yorku.ca

Version: March 23,2021 version of software

Platform: Windows 10, Eclipse version 4.8.0, JavaSE-15

Reproduction:  
1. Paste this guitar tab into text area [guitar_tab_repeat.txt] https://github.com/Stan15/TAB2XML/files/6201170/guitar_tab_repeat.txt)
2.  Press the "Convert" button. 

Expected: "Title" and "Artist" are text fields, thus I expected that once I add some text there it would show up in the output file or file name. The "Conversion method" would provide some options.

Actual: The text entered in the text fields "Title" and "Artist" are not used anywhere. "Conversion method" does not provide any options.
![a](https://user-images.githubusercontent.com/77309918/112400598-169e4980-8cdf-11eb-8123-b0575154c9e5.png)

Priority: Low 

Severity: Low. This bug does not affect the functionality of the code. Title and Artist names are merely for extra information and do not affect the correctness of the output musicXML file. Conversion method should detect the instrument used, however, it is not a huge problem.

**Comment by Stan15** [comment]
Hi. Thanks for letting us know. We are currently working on fixing that bug. I will update you when it is fixed.

**Comment by Stan15** [comment]
this issue has been fixed in the latest version.
