### ISSUE TITLE
Error Highlighting Not Precise

### ISSUE THREAD

**Issue by tuansydau** [Stan15/TAB2XML#16]
**Product**: Tab2XML
**Operating System**: Windows 10
**Opened with**: MuseScore (MuseScore)
**Priority**: minor

**Description**: When converting a guitar tab with an error, the entire measure highlights instead of the individual problem characters.

**Steps to Reproduce Error**:

1. Start the project using Gradle > Run.
2. Enter a valid guitar tab either by copying and pasting the tablature into the text area, or by uploading a file with the File > Open feature.
3. In any given line, enter a string of random and unsupported characters. An example is shown in the screenshot at the end of the issue.

**Expected Behaviour**: The unsupported characters should be highlighted.

**Actual Behaviour**: The entire measure that the error is in is highlighted.

**Screenshots**:
Error highlighting shown below: 
![image](https://user-images.githubusercontent.com/26176104/112407125-e4dfaf80-8ceb-11eb-9f6e-9bfb5a2d9127.png)

**Comment by Stan15** [comment]
Hi. Thanks again for your contribution to the improvement of our software. This issue is not a bug but a feature, explained in the reply given in issue #17
