### ISSUE TITLE
User manual button doesn't open the user manual

### ISSUE THREAD

**Issue by tuansydau** [Stan15/TAB2XML#18]
**Product**: Tab2XML
**Operating System**: Windows 10
**Opened with**: MuseScore (MuseScore)
**Priority**: minor

**Description**: When converting an invalid guitar tab, there is no error message that describes the problem to the user.

**Steps to Reproduce Error**:

1. Start the project using Gradle > Run.
2. On the top-left menu, click "Help", then click "User Manual" in the menu that shows up.

**Expected Behaviour**: The program should lead the user to a user manual of sorts.

**Actual Behaviour**: The help menu closes, and no user manual is opened.

Screenshots:
![image](https://user-images.githubusercontent.com/26176104/112407908-405e6d00-8ced-11eb-9b1c-84ee66b5a208.png)

**Comment by Stan15** [comment]
Hi. Thanks for letting us know. That functionality has been added now.
