### ISSUE TITLE
No error message when inputting a non-tablature

### ISSUE THREAD

**Issue by tommylam16** [Stan15/TAB2XML#19]
### ID
#19

### Who Raised
Tommy Lam

### Title
No error message when inputting a non-tablature

### Version
e2614e6

### Platform
Windows 10, Eclipse, JavaSE-15

### Production
1. Run application
2. Insert code in the textbox
3. Click "Convert"
4. Fill in the given textbok
5.  Click "Save"

### Expected Result
The expected result should output an error message saying the input is not valid

### Actual Result
The actual result does not output any error message and let's the user save the file

### Priority
Priority is Medium

### Severity
Severity is Medium because it is unlikely the user will input a non-tablature file

### Screenshots

**Actual Result**
![g14](https://user-images.githubusercontent.com/77315429/112411236-f6788580-8cf2-11eb-8717-8fc4ccdf689f.PNG)

**Comment by Stan15** [comment]
Hi. Thanks for reporting this issue. I believe this is related to issue #4 which has been fixed. I am unable to recreate the error, so I could only assume that it has been fixed as a side effect of fixing issue #4. I will go ahead and close this issue.
