### ISSUE TITLE
Outputs an empty file for drum tabs

### ISSUE THREAD

**Issue by tommylam16** [Stan15/TAB2XML#20]
### ID
#20

### Who Raised
Tommy Lam

### Title
Outputs an empty file for drum tabs

### Version
e2614e6

### Platform
Windows 10, Eclipse, JavaSE-15

### Production
1. Run application
2.  Insert the following into the textbox:
CC|x---------------|--------x-------|
HH|--x-x-x-x-x-x-x-|----------------|
SD|----o-------o---|oooo------------|
HT|----------------|----oo----------|
MT|----------------|------oo--------|
BD|o-------o-------|o-------o-------|

3. Click "Convert"
4. Fill in the given textbox
5.  Click "Save"
6.  Open up file directory and open the new output file

### Expected Result
The expected result should output the XML of the tablature conversion 

### Actual Result
The actual result output nothing in the file

### Priority
Priority is High

### Severity
Severity is High because it is a System Requirement

### Screenshots

**Actual Result**
![g142](https://user-images.githubusercontent.com/77315429/112411863-f6c55080-8cf3-11eb-8a76-bd8b25f5c07e.PNG)

**Comment by Stan15** [comment]
Thank you for reporting this issue. As previously stated in the user manual, support for drum tablature wasn't added yet. However, in the latest version of our software, we have added support for a number of drum kits. Maybe you could try it out now and see if the errors persist.
