### ISSUE TITLE
Drum Tab Not Converting

### ISSUE THREAD

**Issue by Hartley-Madison-215062417** [Stan15/TAB2XML#21]
Title: Drum Tab Not Converting

Reported By:
Madison hartley

Version:
Commit: e2614e6

Platform:
Windows 10
Java 15
Eclipse 4.18

Reproduction:
Copy the text from this file:
[drumTestTab.txt](https://github.com/Stan15/TAB2XML/files/6201730/drumTestTab.txt)
Launch the converter. Paste text in testbox. Press convert, follow on-screen prompts, and then open the new .xml file.

Expected:
An error message, or, a converted drum xml file.

Actual:
The output file is blank.

Priority:
Low

Severity:
Low

Screenshots:

![nodrum1](https://user-images.githubusercontent.com/46429357/112411768-d4cbce00-8cf3-11eb-842d-58d4d7a3cbc1.PNG)

**Comment by Stan15** [comment]
Hi. To ensure your tablature is properly converted, look at the error messages and ensure that the issues have been resolved. It may have been that some of the drum kits present in the tablature were not supported in this version of the software. However, support for more drum kits have been added in the latest version.

Without further clarification on what the error says (hover over the highlight to see the reason for the error), I am unable to find out what the problem could be.
