### ISSUE TITLE
Song is in wrong key

### ISSUE THREAD

**Issue by Hartley-Madison-215062417** [Stan15/TAB2XML#22]
Title: Song is in wrong key

Reported By:
Madison hartley

Version:
Commit: e2614e6

Platform:
Windows 10
Java 15
Eclipse 4.18

Reproduction:

Start up software. Input the text from this file into the textbox:
[creep.txt](https://github.com/Stan15/TAB2XML/files/6201738/creep.txt)
And then convert. Follow onscreen steps, then open the .xml file.

Expected:

The converted song with the correct key.

Actual:
The song is converted, but with the wrong key. Key is 0 fifths, which is C major, when the tab is in G major, which means fifhts should be 1. There was also no way to manually input this to change it.

Priority:
Low

Severity:
Low

Screenshots:

![creeeppppp](https://user-images.githubusercontent.com/46429357/112412275-a4d0fa80-8cf4-11eb-911e-a9e6c3c95319.PNG)

**Comment by Stan15** [comment]
Thank you for reporting this. Your contribution is highly valued. However, support for custom user-specified key signatures is not planned for the near future.
