### ISSUE TITLE
Notes with slides parsed incorrectly

### ISSUE THREAD

**Issue by tommylam16** [Stan15/TAB2XML#24]
### ID
#24

### Who Raised
Tommy Lam

### Title
Notes with slides parsed incorrectly

### Version
e2614e6

### Platform
Windows 10, Eclipse, JavaSE-15

### Production
1. Run application
2.  Insert the following into the textbox:
![slide](https://user-images.githubusercontent.com/77315429/112412413-d8ac2000-8cf4-11eb-8b1e-21c0be8c51be.PNG)

3. Click "Convert"
4. Fill in the given textbox
5.  Click "Save"
6.  Open up file directory and open the new output file

### Expected Result
The expected result should output the XML showing 6 notes in the second measure along with the note "5" that includes the slide

### Actual Result
The actual result outputs the XML showing 5 notes in the second measure without the note that includes the slide

### Priority
Priority is Medium

### Severity
Severity is Medium because everything is included except the slide and everything else is outputted correctly

### Screenshots

**Expected Result**
![slide](https://user-images.githubusercontent.com/77315429/112412413-d8ac2000-8cf4-11eb-8b1e-21c0be8c51be.PNG)

**Actual Result**
![image](https://user-images.githubusercontent.com/77315429/112413111-047bd580-8cf6-11eb-862a-9f43f22d4712.png)

**Comment by Stan15** [comment]
Thank you for notifying us of this issue. Support for slides have been added in our latest version
