### ISSUE TITLE
Bug Report - Error Highlight Issue

### ISSUE THREAD

**Issue by jamesmqle** [Stan15/TAB2XML#4]
### Error Description: 
The error highlights cannot be seen after you move the tablature past line 2 and then move it back to line 1.

### Priority:
LOW

### Machine/Version:
OS: Windows 10
IDE: IntelliJ version 2020.3.1
Java Version: 15.0.3 

### Steps to Reproduce:
1.	Run the Application
2.	File -> Open -> Load the Following File [test.txt](https://github.com/Stan15/TAB2XML/files/6199689/test.txt) to the Application OR paste the following tablature
```
e|-----------0-----|-0---------------|
B|---------0---0---|-0---------------|
G|-------1-------1-|-1---------------|
D|-----2-----------|-2---------------|
A|---2-------------|-2---------------|
E|-0---------------|-0---------------|  
```
3. Modify the input to replicate the image as seen below.

![image](https://user-images.githubusercontent.com/56422075/112366734-8b598f80-8caf-11eb-890e-cae6353a2044.png)

4. Place your cursor on the first line before the "e" and press enter so the "e" string is now on the second line

![image](https://user-images.githubusercontent.com/56422075/112366787-97455180-8caf-11eb-8889-50fa7d62551b.png)

5. Press the backspace key bringing the "e" string back to the first line

### Expected Result:
The expected result is that the errors remain highlighted throughout these steps.

![image](https://user-images.githubusercontent.com/56422075/112366734-8b598f80-8caf-11eb-890e-cae6353a2044.png)

### Actual Result
The actual result is that the error highlights disappear.
.
![image](https://user-images.githubusercontent.com/56422075/112366896-ad531200-8caf-11eb-9f11-cb1261e57322.png)

###

**Comment by Stan15** [comment]
Hi. Thanks for letting us know of this issue. It has been fixed in the latest version of our software.
