### ISSUE TITLE
Bug Report - Error Highlight Disappear on Window Open

### ISSUE THREAD

**Issue by jamesmqle** [Stan15/TAB2XML#5]
### Error Description: 
The error highlights cannot be seen after you open another window

### Priority:
LOW

### Machine/Version:
OS: Windows 10
IDE: IntelliJ version 2020.3.1
Java Version: 15.0.3 

### Steps to Reproduce:
1.	Run the Application
2.	File -> Open -> Load the Following File [test.txt](https://github.com/Stan15/TAB2XML/files/6199689/test.txt) to the Application OR paste the following tablature

```
e|-----------0-----|-0---------------|
B|---------0---0---|-0---------------|
G|-------1-------1-|-1---------------|
D|-----2-----------|-2---------------|
A|---2-------------|-2---------------|
E|-0---------------|-0---------------|  
```
3. Modify the input to replicate the image as seen below.

![image](https://user-images.githubusercontent.com/56422075/112368716-c066e180-8cb1-11eb-8748-4b620a8ea2ce.png)

4. Press Help -> Settings -> Close Program Settings

### Expected Result:
The errors remain highlighted throughout these steps as seen in the image below.

![image](https://user-images.githubusercontent.com/56422075/112368716-c066e180-8cb1-11eb-8748-4b620a8ea2ce.png)

### Actual Result
The error highlights disappear when the setting windows open. This will cause frustration for the user because when they want to change the settings, they will not see their errors anymore and they would need to restart the application all over again to see them.
.
![image](https://user-images.githubusercontent.com/56422075/112368841-e5f3eb00-8cb1-11eb-9b96-5ba9aea3c2bb.png)

###

**Comment by Stan15** [comment]
Hi. thanks for letting us know. This issue has been fixed in the latest version of our software.
