### ISSUE TITLE
Bug Report - Application Fails when TextArea is Empty on Conversion

### ISSUE THREAD

**Issue by jamesmqle** [Stan15/TAB2XML#6]
### Error Description: 
When nothing is inputted in the text area and a conversion happens, the program will fail. 

### Priority:
MEDIUM

### Machine/Version:
OS: Windows 10
IDE: IntelliJ version 2020.3.1
Java Version: 15.0.3 

### Steps to Reproduce:
1.	Run the Application
2.     Leave the Text Area Empty
3.	Press Convert -> Save

### Expected Result:
There are many possible expected results if no tablature is inputted.

One example would be the UI displays an error message that the input is empty and a conversion never happens. Below is an example of an error message.

![image](https://user-images.githubusercontent.com/56422075/112370665-0a50c700-8cb4-11eb-9530-965af78c947f.png)

### Actual Result
The following errors are shown on the console and an empty XML file is created. 

![image](https://user-images.githubusercontent.com/56422075/112369971-37e94080-8cb3-11eb-9dfb-e920dae14466.png)

Handling this error will depend solely on how the developers want to recreate the user-experience.

###

**Comment by Stan15** [comment]
Hi. thanks for letting us know of this error. A feature has been implemented which prevents conversion until a valid measure is present. I believe this fixes your issue.
