### ISSUE TITLE
No error messages

### ISSUE THREAD

**Issue by NiharikaRajnish** [Stan15/TAB2XML#7]
ID #7
Who Raised: Nia Rajnish
Title: No error messages
Version: Latest version from the master branch
Platform: Mac Os, Eclipse, JavaSE-15
Reproduction:
1. Import and run Program through Gradle 
2. Type anything into the input area (not tablature)
3. Click Convert

Expected:
I expected an error message that explains input text is not a tablature and conversion cannot take place.
Actual:
No error message was displayed. The user is unsure why conversion is not occurring.
Priority:
High priority because this is a system requirement.
Severity:
Low to medium severity since this does not crash the application. Also easy to implement.
Screenshots:
Non tablature text was used as input:
<img width="551" alt="Screen Shot 2021-03-24 at 5 38 06 PM" src="https://user-images.githubusercontent.com/74378254/112387401-18a8de00-8cc8-11eb-909c-101a55c380b1.png">
No error messages displayed:
<img width="560" alt="Screen Shot 2021-03-24 at 5 38 11 PM" src="https://user-images.githubusercontent.com/74378254/112387403-19da0b00-8cc8-11eb-87be-9dea69b0985b.png">

**Comment by Stan15** [comment]
Hi. I believe this is closed as per issue #4
