### ISSUE TITLE
Notes with Slides not Parsed

### ISSUE THREAD

**Issue by NiharikaRajnish** [Stan15/TAB2XML#8]
ID #8
Who Raised: Nia Rajnish
Title: Notes with Slides not Parsed
Version: Latest version from the master branch
Platform: Mac Os, Eclipse, JavaSE-15
Reproduction:
1. Import and run Program through Gradle 
2. Copy and Paste the following test tablature into the input area
3. Click convert and fill in all conversion options
4. Input the .xml file into https://opensheetmusicdisplay.github.io/demo/

Expected:
In the second measure, there are supposed to be 6 notes with the last one being played on fret 5 with a slide.
Actual:
The second measure only includes 5 notes and the last note played on fret 5 with a slide is not included.
Priority:
Medium to low priority since this does not crash/stop the conversion process.
Severity:
Medium to low priority since this does not crash/stop the conversion process.
Screenshots:
Actual Tab (right) versus output tab(left)
<img width="948" alt="Screen Shot 2021-03-24 at 5 29 09 PM" src="https://user-images.githubusercontent.com/74378254/112387654-6de4ef80-8cc8-11eb-9fe1-4b66eec96120.png">

**Comment by Stan15** [comment]
Hi. thanks for letting us know. Support for slides have been added in the latest version of our software.
