### ISSUE TITLE
Blank XML Output File for Drum Tablature

### ISSUE THREAD

**Issue by NiharikaRajnish** [Stan15/TAB2XML#9]
ID #9
Who Raised: Nia Rajnish
Title: Blank XML Output File for Drum Tablature
Version: Latest version from the master branch
Platform: Mac Os, Eclipse, JavaSE-15
Reproduction:
1. Import and run Program through Gradle 
2. Copy and Paste the following text tablature into the input area
[drums_tab.txt](https://github.com/Stan15/TAB2XML/files/6200654/drums_tab.txt)
3. Click convert and fill in all conversion options according to screenshot below.
4. Open the output file.

Expected:
I expected a Music xml file with all the necessary tags/information
Actual:
The output .xml file was completely blank. Drum tablature parsing is not implemented yet. 
Priority:
High priority since this is a system requirement
Severity:
High severity since this is a system requirement.
Screenshots:
Input/Convertion Options
<img width="573" alt="Screen Shot 2021-03-24 at 5 28 48 PM" src="https://user-images.githubusercontent.com/74378254/112388147-18f5a900-8cc9-11eb-84d4-c7d4ee5df262.png">

Output .XML file
<img width="766" alt="Screen Shot 2021-03-24 at 5 28 55 PM" src="https://user-images.githubusercontent.com/74378254/112388155-1c893000-8cc9-11eb-9eee-9c965566fc74.png">

**Comment by Stan15** [comment]
Hi. Thanks for reporting this issue. However, at the time, as stated in our user manual, there was no support for drum tablature. However, support has been added for a number of drum parts in the latest version of our software.
